"""Initial migration.

Revision ID: 451aa0e986c5
Revises: 
Create Date: 2020-03-28 20:34:07.321929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451aa0e986c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_image', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_type'), 'users', ['user_type'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('student',
    sa.Column('usn', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=140), nullable=True),
    sa.Column('last_name', sa.String(length=140), nullable=True),
    sa.Column('address', sa.String(length=240), nullable=True),
    sa.Column('branch', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('usn'),
    sa.UniqueConstraint('usn')
    )
    op.create_table('teacher',
    sa.Column('t_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=140), nullable=True),
    sa.Column('last_name', sa.String(length=140), nullable=True),
    sa.Column('branch', sa.String(length=140), nullable=True),
    sa.Column('address', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('t_id'),
    sa.UniqueConstraint('t_id')
    )
    op.create_table('branch',
    sa.Column('branch_id', sa.String(length=40), nullable=False),
    sa.Column('sem', sa.String(length=140), nullable=True),
    sa.Column('sec', sa.String(length=140), nullable=True),
    sa.Column('usns', sa.String(length=140), nullable=False),
    sa.ForeignKeyConstraint(['usns'], ['student.usn'], ),
    sa.PrimaryKeyConstraint('branch_id'),
    sa.UniqueConstraint('branch_id')
    )
    op.create_table('attendance',
    sa.Column('day', sa.String(length=140), nullable=False),
    sa.Column('time', sa.String(length=140), nullable=True),
    sa.Column('Subject', sa.String(length=140), nullable=True),
    sa.Column('branch', sa.String(length=140), nullable=False),
    sa.Column('sem', sa.String(length=140), nullable=True),
    sa.Column('sec', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['branch'], ['branch.branch_id'], ),
    sa.PrimaryKeyConstraint('day'),
    sa.UniqueConstraint('day')
    )
    op.create_table('subject',
    sa.Column('sub_id', sa.String(length=40), nullable=False),
    sa.Column('sub_name', sa.String(length=140), nullable=True),
    sa.Column('Branch', sa.String(length=140), nullable=False),
    sa.ForeignKeyConstraint(['Branch'], ['branch.branch_id'], ),
    sa.PrimaryKeyConstraint('sub_id'),
    sa.UniqueConstraint('sub_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject')
    op.drop_table('attendance')
    op.drop_table('branch')
    op.drop_table('teacher')
    op.drop_table('student')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_type'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
